### PR TITLE
Fix import and Elemwise optimization issues

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR fixes the currently failing optimization tests and some import issues that were also introduced in #21.  It also contains some relevant refactoring.

UPDATE: See #58 for an alternative PR that could fix these issues sooner than this one.

### CODE REVIEW

**Comment by twiecki** [comment]
Great stuff, this cleans up *a lot*.

```python
sts/test_2nd_order_grads.py:5: in <module>

    import theano

theano/__init__.py:94: in <module>

    from theano.configdefaults import config

theano/configdefaults.py:623: in <module>

    "mode", "Default compilation mode", ConfigParam("Mode", filter_mode), in_c_key=False

theano/configparser.py:301: in AddConfigVar

    configparam.__get__(root, type(root), delete_key=True)

theano/configparser.py:347: in __get__

    self.__set__(cls, val_str)

theano/configparser.py:359: in __set__

    self.val = self.filter(val)

theano/configdefaults.py:607: in filter_mode

    or val in theano.compile.mode.predefined_modes

E   AttributeError: module 'theano' has no attribute 'compile'
```

**Comment by brandonwillard** [comment]
Ha, yeah, this is the result of #45.

**Comment by brandonwillard** [comment]
Superceded by #58.
